
package org.econfortin.ocejwsdstudy.enthuware.test1.q36;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LogLog", targetNamespace = "http://q36.test1.enthuware.ocejwsdstudy.econfortin.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogLog {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "log", targetNamespace = "http://q36.test1.enthuware.ocejwsdstudy.econfortin.org/", className = "org.econfortin.ocejwsdstudy.enthuware.test1.q36.Log")
    @ResponseWrapper(localName = "logResponse", targetNamespace = "http://q36.test1.enthuware.ocejwsdstudy.econfortin.org/", className = "org.econfortin.ocejwsdstudy.enthuware.test1.q36.LogResponse")
    public void log(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
