
package org.econfortin.ocejwsdstudy.enthuware.test1.q36;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LogWebService", targetNamespace = "http://q36.test1.enthuware.ocejwsdstudy.econfortin.org/", wsdlLocation = "http://localhost:8080/ocejwsdstudy/LogWebService?wsdl")
public class LogWebService
    extends Service
{

    private final static URL LOGWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.econfortin.ocejwsdstudy.enthuware.test1.q36.LogWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.econfortin.ocejwsdstudy.enthuware.test1.q36.LogWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ocejwsdstudy/LogWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ocejwsdstudy/LogWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOGWEBSERVICE_WSDL_LOCATION = url;
    }

    public LogWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogWebService() {
        super(LOGWEBSERVICE_WSDL_LOCATION, new QName("http://q36.test1.enthuware.ocejwsdstudy.econfortin.org/", "LogWebService"));
    }

    /**
     * 
     * @return
     *     returns LogLog
     */
    @WebEndpoint(name = "LogLogPort")
    public LogLog getLogLogPort() {
        return super.getPort(new QName("http://q36.test1.enthuware.ocejwsdstudy.econfortin.org/", "LogLogPort"), LogLog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogLog
     */
    @WebEndpoint(name = "LogLogPort")
    public LogLog getLogLogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://q36.test1.enthuware.ocejwsdstudy.econfortin.org/", "LogLogPort"), LogLog.class, features);
    }

}
